name: release-us
on:
  push:
    tags: ['v*.*.*']

permissions:
  contents: read

jobs:
  release:
    environment: us-web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Pack web
        run: |
          test -d web || mkdir -p web && echo placeholder > web/README.txt
          date +%Y%m%d-%H%M%S > web/__version
          tar -czf web_build.tgz web

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.US_SSH_KEY }}

      - name: Add known_hosts
        run: |
          mkdir -p ~/.ssh
          printf '%s\n' "${{ secrets.KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

      - name: Upload and switch on US
        env:
          HOST: ${{ secrets.US_HOST }}
          PORT: ${{ secrets.US_PORT }}
          USER: ${{ secrets.US_USER }}
          BASE: ${{ secrets.US_PATH }}
          TAG:  ${{ github.ref_name }}
        run: |
          ssh -p "$PORT" $USER@$HOST "mkdir -p $BASE/releases/$TAG"
          scp -P "$PORT" web_build.tgz $USER@$HOST:$BASE/releases/$TAG/
          ssh -p "$PORT" $USER@$HOST bash -lc "
            set -e
            cd $BASE/releases/$TAG
            tar -xzf web_build.tgz
            ln -nfs $BASE/releases/$TAG $BASE/current
            sudo systemctl reload nginx || true
            test -f $BASE/current/web/__version
          "
